-- All users, assignments, rentals and blocks are transaction-local test fixtures.
begin;
do $$
declare pending_id uuid;foreign_id uuid;p uuid;q uuid;u1 uuid:=gen_random_uuid();u2 uuid:=gen_random_uuid();a uuid;b uuid;r uuid;mine uuid;theirs uuid;n integer;admin_id uuid;
begin
 select id into admin_id from auth.users where lower(email)='info@lehmann-gt.ch';
 insert into auth.users(id,email,email_confirmed_at,is_anonymous) values(u1,'fixture-'||u1||'@example.com',now(),false),(u2,'fixture-'||u2||'@example.com',now(),false);
 insert into public.products(slug,category,name,day_price,active) values('fixture-'||gen_random_uuid(),'Gartengeräte','Partnergerät',100,true) returning id into p;
 insert into public.products(slug,category,name,day_price,active) values('fixture-'||gen_random_uuid(),'Gartengeräte','Fremdgerät',100,true) returning id into q;
 insert into public.units(product_id,internal_name) values(p,'Partnergerät #1'),(q,'Fremdgerät #1');
 insert into public.rental_partners(user_id,company,email,notification_email) values(u1,'Testfirma A','fixture-'||u1||'@example.com','a@example.com') returning id into a;
 insert into public.rental_partners(user_id,company,email,notification_email) values(u2,'Testfirma B','fixture-'||u2||'@example.com','b@example.com') returning id into b;
 insert into public.rental_partner_devices(partner_id,product_id) values(a,p),(b,p);
 perform set_config('request.jwt.claims',json_build_object('role','authenticated','sub',u1)::text,true);
 set local role authenticated;
 if public.rental_access_role()<>'sublessor' then raise exception 'Partner role missing';end if;
 select count(*) into n from public.partner_inventory();if n<>1 then raise exception 'Incorrect inventory scope';end if;
 select count(*) into n from public.admin_reservations;if n<>0 then raise exception 'Partner can read admin reservations';end if;
 select count(*) into n from public.reservation_customers;if n<>0 then raise exception 'Partner can read customers';end if;
 select count(*) into n from public.rental_email_templates;if n<>0 then raise exception 'Partner can read email settings';end if;
 update public.products set day_price=1 where id=p;get diagnostics n=row_count;if n<>0 then raise exception 'Partner can change price';end if;
 update public.rental_partners set notification_email='bad@example.com' where id=a;get diagnostics n=row_count;if n<>0 then raise exception 'Partner can change routing';end if;
 begin perform public.partner_calendar(q,'2091-01-01',14);raise exception 'UNEXPECTED allowed foreign calendar';exception when raise_exception then if SQLERRM like 'UNEXPECTED%' then raise;end if;end;
 begin perform public.partner_create_block(q,'2091-01-01','2091-01-02','am','pm','test');raise exception 'UNEXPECTED allowed foreign block';exception when raise_exception then if SQLERRM like 'UNEXPECTED%' then raise;end if;end;
 begin perform public.admin_create_rental_v2(p,'2091-01-01','2091-01-02','am','pm','Test',null,null,'000',null,null,false,'confirmed');raise exception 'UNEXPECTED legacy admin rental';exception when raise_exception then if SQLERRM like 'UNEXPECTED%' then raise;end if;end;
 begin perform public.admin_create_rental(p,'2091-01-01','2091-01-02','full','Test',null,null,'000',null,null,false,'confirmed');raise exception 'UNEXPECTED oldest admin rental';exception when raise_exception then if SQLERRM like 'UNEXPECTED%' then raise;end if;end;
 begin perform public.create_rental_block_v2(p,'2091-01-01','2091-01-02','am','pm','test');raise exception 'UNEXPECTED admin block';exception when raise_exception then if SQLERRM like 'UNEXPECTED%' then raise;end if;end;
 begin perform public.create_rental_block(p,'2091-01-01','2091-01-02','full','test');raise exception 'UNEXPECTED oldest admin block';exception when raise_exception then if SQLERRM like 'UNEXPECTED%' then raise;end if;end;
 begin perform public.admin_save_product(p,'Gartengeräte','Changed',null,1,null,null,false,null,true,1,1);raise exception 'UNEXPECTED admin product';exception when raise_exception then if SQLERRM like 'UNEXPECTED%' then raise;end if;end;
 begin perform public.admin_save_partner(a,'Changed','bad@example.com','bad@example.com',true,array[q]);raise exception 'UNEXPECTED self assignment';exception when raise_exception then if SQLERRM like 'UNEXPECTED%' then raise;end if;end;
 mine:=public.partner_create_block(p,'2091-01-01','2091-01-02','pm','pm','Privat');if mine is null then raise exception 'Partner block failed';end if;
 if public.partner_create_block(p,'2091-01-01','2091-01-02','pm','pm','Privat') is not null then raise exception 'Partner overbooking';end if;
 select count(*) into n from public.partner_blocks();if n<>1 then raise exception 'Own block missing';end if;
 reset role;
 perform set_config('request.jwt.claims',json_build_object('role','authenticated','sub',u2)::text,true);
 set local role authenticated;
 begin perform public.partner_remove_block(mine);raise exception 'UNEXPECTED deleting another partner block';exception when raise_exception then if SQLERRM like 'UNEXPECTED%' then raise;end if;end;
 theirs:=public.partner_create_block(p,'2091-01-03','2091-01-03','am','pm','Zweite Firma');
 reset role;
 perform set_config('request.jwt.claims',json_build_object('role','authenticated','sub',admin_id)::text,true);
 set local role authenticated;
 if public.rental_access_role()<>'admin' then raise exception 'Admin access regression';end if;
 if public.admin_create_rental_v3(p,'2091-01-01','2091-01-02','pm','pm','Test',null,null,'000',null,null,false,'confirmed',null,null) is not null then raise exception 'Admin overwrites partner block';end if;
 r:=public.admin_create_rental_v3(p,'2091-01-04','2091-01-05','pm','pm','Test',null,null,'000',null,null,false,'confirmed',null,null);
 if r is null then raise exception 'Admin cannot rent assigned device';end if;
 select count(*) into n from public.rental_direct_notifications where reservation_id=r and sent_at is null;if n<>1 then raise exception 'Direct notification not queued without customer email';end if;
 select count(*) into n from public.admin_reservations where id=mine;if n<>1 then raise exception 'Admin cannot see partner block';end if;
 pending_id:=public.admin_create_rental_v3(p,'2091-02-01','2091-02-02','am','pm','Scoped customer',null,'fixture@example.com','000',null,null,false,'pending',null,null);
 foreign_id:=public.admin_create_rental_v3(q,'2091-02-01','2091-02-02','am','pm','Foreign customer',null,'fixture@example.com','000',null,null,false,'pending',null,null);

 reset role;
 perform set_config('request.jwt.claims',json_build_object('role','authenticated','sub',u1)::text,true);
 set local role authenticated;

 if not exists(select 1 from jsonb_array_elements(public.partner_reservations()) x where x->>'id'=pending_id::text) then raise exception 'Assigned request missing';end if;
 if exists(select 1 from jsonb_array_elements(public.partner_reservations()) x where x->>'id'=foreign_id::text or x ?| array['name','email','phone','address','company','note']) then raise exception 'Customer data exposed';end if;
 if not public.partner_remove_block(mine) then raise exception 'Own block removal failed';end if;
 mine:=public.partner_create_block(p,'2091-01-06','2091-01-06','am','pm','Privat');
 reset role;
 delete from public.rental_partner_devices where partner_id=a;
 set local role authenticated;
 select count(*) into n from public.partner_inventory();if n<>0 then raise exception 'Revoked device remains visible';end if;
 if jsonb_array_length(public.partner_reservations())<>0 then raise exception 'Revoked customer access';end if;

 begin perform public.partner_remove_block(mine);raise exception 'UNEXPECTED revoked device access';exception when raise_exception then if SQLERRM like 'UNEXPECTED%' then raise;end if;end;
 reset role;
 update public.rental_partners set active=false where id=a;
 set local role authenticated;
 if public.rental_access_role()<>'none' then raise exception 'Disabled partner retains access';end if;
 reset role;
end $$;
rollback;
select 'PASS: role isolation, legacy admin protection, scoped inventory, own blocks, capacity, immediate revocation and queued direct notification without customer email; fixtures rolled back' as result;
